version: '3.8'

networks:
  private:
  proxy:
    external: true

services:
  db:
    image: postgres:12-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    networks:
      - private

  web:
    image: andrey8606/ilr_league:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    depends_on:
      - db
    env_file:
      - ./.env
    networks:
      - private

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    expose:
      - 80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    environment:
      VIRTUAL_HOST: running-league.ilovesupersport.com
      LETSENCRYPT_HOST: running-league.ilovesupersport.com
    networks:
      - private
      - proxy
    depends_on:
      - web

volumes:
  postgres_data:
  static_value:
  media_value:
